# fly.toml app configuration file generated for habit-hero-back on 2023-06-09T07:57:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "habit-hero-back"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
